// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL3aoWRRs6nI2DOsi4S1kyr6irB_By_BM',
    appId: '1:637178412358:web:7fef783ddcbea8e2ecb947',
    messagingSenderId: '637178412358',
    projectId: 'some-practices',
    authDomain: 'some-practices.firebaseapp.com',
    storageBucket: 'some-practices.firebasestorage.app',
    measurementId: 'G-DR88MC5JX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3TdTSq-sN0OnnKyGvBQdb4mqcLROfk0',
    appId: '1:637178412358:android:5be432773bf233edecb947',
    messagingSenderId: '637178412358',
    projectId: 'some-practices',
    storageBucket: 'some-practices.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL3aoWRRs6nI2DOsi4S1kyr6irB_By_BM',
    appId: '1:637178412358:web:6edb65245ed026d8ecb947',
    messagingSenderId: '637178412358',
    projectId: 'some-practices',
    authDomain: 'some-practices.firebaseapp.com',
    storageBucket: 'some-practices.firebasestorage.app',
    measurementId: 'G-WLKJ67X8GG',
  );
}
